# Site Settings

paginate:            5
disqus:              "https-partidadoble-github-io"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]

# run: jekyll serve